### ISSUE TITLE
Request for unofficial clarification

### ISSUE THREAD

**Issue by tagawa** [pistom/ddghur#7]
Hi. Thanks for making this add-on to help people use DuckDuckGo more easily.

Unfortunately we (DuckDuckGo) sometimes hear about users being confused about what's an official add-on and what isn't. To avoid this confusion, please could you:

- Change the logo so it doesn't feature the "Dax the duck" mascot,
- Make it clear your usage is "unofficial" in the description?

Thanks in advance.

**Comment by pistom** [comment]
Hello. No problem. I just added the changes and published them.
Have a nice day :)

**Comment by tagawa** [comment]
Hi again. That's great – thank you very much for the quick action.

I'd love to send you a t-shirt as a small token of thanks. If you'd like that, please send me an email at daniel at duckduckgo dot com
