### ISSUE TITLE
Firefox update broke plugin

### ISSUE THREAD

**Issue by alaestor** [pistom/ddghur#9]
Edit: **If this project is deprecated**, you should redirect users to [your other plugin](https://github.com/pistom/hohser) as that one seems to be working still

I've found that the plugin hasn't functioned properly for the past couple months. It hasn't been removing unwanted results. Based on [recent negative reviews](https://addons.mozilla.org/en-US/firefox/addon/ddg-hide-unwanted-results/reviews/), other users have been experiencing this as well.

**Comment by pistom** [comment]
Thank you for letting me know. Indeed, I no longer develop this project. Sorry for the inconvenience
